sql_alchemy/models/__init__.py
from flask_login import LoginManager,UserMixin
from sqlalchemy  import create_engine, ForeignKey
from sqlalchemy.orm import Session,Mapped, mapped_column, relationship,DeclarativeBase

#cria a engine
engine = create_engine('sqlite:///database/database.db')
# cria uma sessão do sqlalchemy
# serve para executar as operações no banco, como: adicionar, selecionar, excluir e etc.
session = Session(bind=engine)

login_manager = LoginManager()


#definição da classe base
class Base(DeclarativeBase):
    pass

class User(Base, UserMixin):
    __tablename__ = 'tb_usuarios'
    usu_id:Mapped[int] = mapped_column(primary_key=True)
    usu_nome:Mapped[str]
    usu_email:Mapped[str] = mapped_column(unique=True)
    usu_senha:Mapped[str]
    # define o relacionamento 1:n entre user e livro. Retorna uma lista.
    livro = relationship('Livro', backref='user')
    def get_id(self):
        return str(self.usu_id)
    def All():
        return session.query(User).all()

class Livro(Base):
    __tablename__ = 'tb_livros'
    liv_id:Mapped[int] = mapped_column(primary_key=True)
    liv_titulo:Mapped[str]
    # define a foreign key
    liv_usu_id:Mapped[int] = mapped_column(ForeignKey('tb_usuarios.usu_id'))
    def All():
        return session.query(Livro).all()

sql_alchemy/app.py
from flask import Flask, render_template
from models import Base, Livro
from models import login_manager,engine
from controllers.users import auth_bp
from controllers.books import bp
app = Flask(__name__)

app.config['SECRET_KEY'] = 'VASCÃO'

# iniciar flask login
login_manager.init_app(app)

#cria o banco de dados
Base.metadata.create_all(bind=engine)

app.register_blueprint(auth_bp)
app.register_blueprint(bp)

@app.route('/')
def index():
    return render_template('index.html')

sql_alchemy/controllers/books.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import  login_required, current_user
from models import session, Livro,User
bp = Blueprint('book', __name__, url_prefix='/books')


@bp.route('/')
@login_required
def index():
    return render_template('book/index.html', livros=Livro.All())

@bp.route('/cadastro', methods=['POST','GET'])
@login_required
def cadastro():
    if request.method == 'POST':
        titulo = request.form['titulo']
        autor = current_user.usu_id
        book_new = Livro(liv_titulo=titulo, liv_usu_id=autor)
        session.add(book_new)
        session.commit()
        return redirect(url_for('book.index'))
    return render_template('book/cadastro.html')

sql_alchemy/controllers/users.py
from flask import Blueprint, render_template, request, redirect,url_for
from models import session, login_manager
from models import User
from sqlalchemy import select
from flask_login import login_user, logout_user, login_required

auth_bp = Blueprint('user', __name__, url_prefix='/users')


@login_manager.user_loader
def load_user(user_id):
    return session.query(User).get(user_id)

@auth_bp.route('/')
def index():
    return render_template('user/index.html', users=User.All())

@auth_bp.route('/login', methods=['POST','GET'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        senha = request.form['senha']
        user = session.query(User).filter_by(usu_email=email).first()
        if user.usu_email == email and user.usu_senha == senha:
            login_user(user)
            return redirect(url_for('user.index'))
        return redirect(url_for('user.login'))
    return render_template('user/login.html')

@auth_bp.route('/cadastro', methods=['POST','GET'])
def cadastro():
    if request.method == 'POST':
        nome = request.form['nome']
        email = request.form['email']
        senha = request.form['senha']
        emails = session.execute(select(User.usu_email)).scalars().all()
        if email in emails:
            return redirect(url_for('user.index'))
        user = User(usu_nome=nome, usu_email=email,usu_senha=senha)
        session.add(user)
        session.commit()
        return redirect(url_for('user.index'))
    return render_template('user/cadastro.html')

@auth_bp.route('/logout', methods=['POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.index'))

sql_alchemy/templates/book/cadastro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Cadastro de livros</h1>
    <hr>
    <form action="{{url_for('book.cadastro')}}" method="post">
        <input type="text" name="titulo" placeholder="Titulo">
        <input type="submit" value="enviar">
    </form>
</body>
</html>

sql_alchemy/templates/book/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Books</h1>
    <a href="{{url_for('book.cadastro')}}">Cadastro</a>|
    <a href="{{url_for('user.index')}}">Users</a>
    <hr>
    {% for livro in livros %}
        <p>Titulo: {{livro.liv_titulo}}| Autor(a): {{livro.user.usu_nome}}</p>
    {% endfor %}
</body>
</html>

sql_alchemy/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Inicio</h1>
    <a href="{{url_for('user.index')}}">users</a>|
    <a href="{{url_for('book.index')}}">Books</a>
    <hr>
</body>
</html>

sql_alchemy/templates/user/cadastro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Cadastro de users</h1>
    <hr>
    <form action="{{url_for('user.cadastro')}}" method="post">
        <input type="text" name="nome" placeholder="Nome" required>
        <input type="email" name="email" placeholder="Email" required>
        <input type="password" name="senha" placeholder="Senha" required>
        <input type="submit" value="enviar">
    </form>
</body>
</html>

sql_alchemy/templates/user/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Users</h1>
    <a href="{{url_for('user.cadastro')}}">Cadastro</a>|
    {% if current_user.is_authenticated %}
    <form action="{{url_for('user.logout')}}" method="post">
        <input type="submit" value="logout">
    </form>
    {% else %}
    <a href="{{url_for('user.login')}}">Login</a>
    {% endif %}|
    <a href="{{url_for('book.index')}}">Books</a>
    <hr>
    {% for user in users %}
        <p>{{user.usu_nome}}</p>
    {% endfor %}
</body>
</html>

sql_alchemy/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Login</h1>
    <hr>
    <form action="{{url_for('user.login')}}" method="post">
        <input type="email" name="email" placeholder="email">
        <input type="password" name="senha" placeholder="senha">
        <input type="submit" value="enviar">
    </form>
</body>
</html>